version: '3.3'


services:
 
 mariadb:
  image: mariadb:${MYSQL_VERSION}
  container_name: maridb-dev
  restart: always
  ports:
   - ${MYSQL_PORT_LOCAL}:${MYSQL_PORT_DEFAULT}
  environment:
   MYSQL_ROOT_PASSWORD: ${MY_MYSQL_ROOT_PASSWORD}
   MYSQL_USER: ${MY_MYSQL_USER}
   MYSQL_PASSWORD: ${MY_MYSQL_USER_PASSWORD}
   MYSQL_DATABASE: ${MY_MYSQL_DB}
  volumes:
   - ./mysql/db:/var/lib/mysql
   - ./mysql/log:/var/lib/log
  networks:
   - databases

 postgres:
  image: postgres:${POSTGRES_VERSION}
  container_name: postgres-dev
  restart: always
  ports:
   - ${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT_DEFAULT}
  environment:
   POSTGRES_ROOT_PASSWORD: ${MY_POSTGRES_ROOT_PASSWORD}
   POSTGRES_USER: ${MY_POSTGRES_USER}
   POSTGRES_PASSWORD: ${MY_POSTGRES_USER_PASSWORD}
   POSTGRES_DB: ${MY_POSTGRES_DB}
  volumes:
   - ./postgres/db:/var/lib/postgresql/data
   - ./postgres/log:/var/lib/postgresql/log
  networks:
   - databases

 firebird:
    image: kpsys/firebird
    container_name: firebird-dev
    volumes:
     - ./firebird/db:/usr/local/firebird/data
    ports:
      - ${FIREBIRD_PORT_LOCAL}:${FIREBIRD_PORT_DEFAULT}
    networks:
      - databases

 mongo:
  image: mongo:${MONGO_VERSION}
  container_name: mongo-dev
  restart: always
  ports:
   - ${MONGO_PORT_LOCAL}:${MONGO_PORT_DEFAULT}
  volumes:
   - ./mongo/db:/data/db
  networks:
   - databases

 redis:
  image: redis:${REDIS_VERSION}
  container_name: redis-dev
  restart: always
  ports:
   - ${REDIS_PORT_LOCAL}:${REDIS_PORT_DEFAULT}
  volumes:
   - ./redis/db:/data
  networks:
   - databases
   
networks:
 databases:
