version: '3.3'

services:
 nginx:
  image: nginx:${NGINX_VERSION}
  container_name: nginx-dev
  restart: always
  ports:
   - ${PORT}:80
   - ${PORT_SSL}:443
  volumes:
   - ../public_html/:/usr/share/nginx/html:rw
   - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
   - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  networks:
   - php-fpm
   - db
   - web
networks:
 web:
 db:
  external:
   name: databases_databases   
 php-fpm:
  external:
   name: php_php-fpm

